### ISSUE TITLE
文章

### ISSUE THREAD

**Issue by ZTurboX** [thunlp/Chinese_NRE#1]
请问文章什么时候可以放上来，想学习一下

**Comment by BMDN** [comment]
你好，论文会由ACL的正常流程出版，欢迎交流指正

**Comment by dingn42** [comment]
> 请问文章什么时候可以放上来，想学习一下

你好，论文会由ACL的正常流程出版，欢迎交流指正

**Comment by feng-1985** [comment]
arxiv上还没放？
