### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by ysn7** [thunlp/Chinese_NRE#4]
在test文档中，第一列的实体和第二列的实体顺序是否不可改变，必须是句子中先出现的在前，后出现的在后

**Comment by ML-PPAP** [comment]
我想请问一下vec.txt、sense_map.txt、sense.txt文件为什么没有，是我哪里做的不对么，望指点

**Comment by zpli0320** [comment]
给的数据文件sense.txt最后一行"铛铛车"的embedding缺失了一小段数值，长度才175，其他都是201

**Comment by ML-PPAP** [comment]
谢谢您的解答！thank&nbsp;you！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zpli0320"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月25日(星期五) 晚上8:47
收件人:&nbsp;"thunlp/Chinese_NRE"<Chinese_NRE@noreply.github.com&gt;;
抄送:&nbsp;"ゞ"<827250833@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/Chinese_NRE] 关于数据集 (#4)




给的数据文件sense.txt最后一行"铛铛车"的embedding缺失了一小段数值，长度才175，其他都是201

**Comment by dfxliziran** [comment]
> 在test文档中，第一列的实体和第二列的实体顺序是否不可改变，必须是句子中先出现的在前，后出现的在后

顺序是可变的：如果关系是双向的，则改变顺序后对应的关系也会改变；如果关系不区分方向，则改变顺序后关系不变

**Comment by dfxliziran** [comment]
> 我想请问一下vec.txt、sense_map.txt、sense.txt文件为什么没有，是我哪里做的不对么，望指点

这三个文件的网盘链接在readme里有提供
