### ISSUE TITLE
数据文件有错

### ISSUE THREAD

**Issue by zpli0320** [thunlp/Chinese_NRE#5]
给的数据文件sense.txt最后一行"铛铛车"的embedding缺失了一小段数值，长度才175，其他都是201

**Comment by dfxliziran** [comment]
应该是没有错的。我刚刚重新下载了一份检查没有问题，本地的也是一样。可能是你没下全，可以试试再下一次，并注意对比下载的文件大小是否与网盘上提供的文件大小相同。
