### ISSUE TITLE
关于sense和sensemap

### ISSUE THREAD

**Issue by wangyankiko** [thunlp/Chinese_NRE#7]
在github上看见了你们组的论文，想了解一下sense.txt和sense_map.txt怎么生成呀？想学习一下你们的代码。请问sense.txt是在这里下载那个sense-vec.txt吗？https://cloud.tsinghua.edu.cn/d/76ab4a71efa541bd8eb3/

**Comment by dingn42** [comment]
已在邮件中回复

**Comment by wangyankiko** [comment]
谢谢
